import type { AgentDef } from "@/types/agents";

export const AGENTS: AgentDef[] = [
  {
    slug: "lead",
    name: "Lead",
    role: "Team Lead",
    color: "indigo",
    colorHex: "#6366f1",
    description: "Coordinates the team, creates tasks, and drives the build from brief to deployment.",
    skills: [
      { name: "Task management", description: "Creates and assigns tasks, tracks progress, and unblocks teammates" },
      { name: "Team coordination", description: "Orchestrates parallel agent work and resolves cross-team dependencies" },
      { name: "Project planning", description: "Translates a brief into a sequenced build plan with clear milestones" },
    ],
    owns: ["contracts-evm/script/", "README.md", ".env.example", ".gitignore"],
  },
  {
    slug: "mochi",
    name: "Mochi",
    role: "Ideator",
    color: "pink",
    colorHex: "#ec4899",
    description: "Researches and brainstorms project ideas, then writes the brief that kicks off every build.",
    skills: [
      { name: "Ideation", description: "Generates creative project concepts grounded in Web3 and onchain trends" },
      { name: "Web research", description: "Surveys existing projects, market gaps, and technical feasibility" },
      { name: "Product thinking", description: "Frames ideas around user needs and viable product scopes" },
    ],
    owns: ["docs/brief.md"],
  },
  {
    slug: "blueprint",
    name: "Blueprint",
    role: "Architect",
    color: "cyan",
    colorHex: "#06b6d4",
    description: "Designs the full technical specification — contracts, API, frontend, and how everything connects.",
    skills: [
      { name: "System design", description: "Defines data models, component boundaries, and integration points across the stack" },
      { name: "Solidity architecture", description: "Designs contract interfaces, storage layouts, and upgrade patterns" },
      { name: "API contracts", description: "Specifies REST endpoints, request/response shapes, and error handling" },
      { name: "Next.js patterns", description: "Plans page routing, data fetching strategy, and API route structure" },
    ],
    owns: ["docs/spec.md", "docs/architecture.md"],
  },
  {
    slug: "forge",
    name: "Forge",
    role: "Smart Contract Dev",
    color: "orange",
    colorHex: "#f97316",
    description: "Writes and tests EVM smart contracts in Solidity using Foundry and OpenZeppelin.",
    skills: [
      { name: "Solidity", description: "Writes production-quality Solidity ^0.8.24 contracts with gas efficiency in mind" },
      { name: "Foundry", description: "Uses Forge for compilation, fuzz testing, and scripted deployments" },
      { name: "OpenZeppelin", description: "Extends audited OZ base contracts for ERC20, ERC721, access control, and more" },
      { name: "EVM deployment", description: "Deploys and verifies contracts on Etherlink Shadownet and Mainnet" },
    ],
    owns: ["contracts-evm/src/", "contracts-evm/test/", "contracts-evm/foundry.toml"],
  },
  {
    slug: "naga",
    name: "Naga",
    role: "Tezos L1 Dev",
    color: "teal",
    colorHex: "#14b8a6",
    description: "Builds SmartPy contracts on Tezos L1, including FA2 tokens and custom on-chain logic.",
    skills: [
      { name: "SmartPy", description: "Authors and tests Tezos smart contracts in SmartPy v0.17+" },
      { name: "Tezos L1", description: "Deploys and interacts with contracts on Tezos Mainnet and Ghostnet" },
      { name: "FA2 tokens", description: "Implements multi-asset FA2 token standards for NFTs and fungible tokens" },
      { name: "Tezos tooling", description: "Uses Octez client, tezos-client, and tzkt APIs for contract management" },
    ],
    owns: ["contracts-tezos/src/", "contracts-tezos/tests/"],
  },
  {
    slug: "link",
    name: "Link",
    role: "Backend Dev",
    color: "blue",
    colorHex: "#3b82f6",
    description: "Builds the API layer — Next.js routes, contract helpers, database clients, and TypeScript types.",
    skills: [
      { name: "Next.js API routes", description: "Builds server-side API routes with proper error handling and type safety" },
      { name: "TypeScript", description: "Defines shared types and interfaces consumed by both backend and frontend" },
      { name: "Etherlink API", description: "Integrates Blockscout v2 REST API for on-chain data queries and contract interaction" },
      { name: "Database integration", description: "Connects Supabase or Prisma for persistent off-chain data storage" },
    ],
    owns: ["frontend/src/lib/", "frontend/src/app/api/", "frontend/src/types/"],
  },
  {
    slug: "pixel",
    name: "Pixel",
    role: "Frontend Dev",
    color: "purple",
    colorHex: "#a855f7",
    description: "Builds all UI — pages, components, hooks, and the visual design in Tailwind CSS.",
    skills: [
      { name: "React", description: "Builds composable, accessible React components with clean state management" },
      { name: "Next.js", description: "Implements App Router pages, layouts, and client/server component boundaries" },
      { name: "Tailwind CSS", description: "Styles UIs with utility-first Tailwind v3, including custom themes and animations" },
      { name: "UI/UX", description: "Translates specs into polished, user-friendly interfaces with consistent design" },
      { name: "Animations", description: "Adds motion with Framer Motion or CSS transitions to enhance user experience" },
    ],
    owns: ["frontend/src/app/", "frontend/src/components/", "frontend/src/hooks/"],
  },
  {
    slug: "sage",
    name: "Sage",
    role: "Reviewer",
    color: "yellow",
    colorHex: "#eab308",
    description: "Reviews all code for correctness, security, and build health. Finds issues and messages teammates.",
    skills: [
      { name: "Code review", description: "Audits code for logic errors, edge cases, and adherence to project conventions" },
      { name: "Security auditing", description: "Identifies common vulnerabilities including reentrancy, overflow, and injection risks" },
      { name: "Build verification", description: "Runs tsc and npm build to confirm the project compiles cleanly" },
      { name: "TypeScript", description: "Catches type errors and enforces strict type safety across the codebase" },
    ],
    owns: [],
  },
  {
    slug: "rocket",
    name: "Rocket",
    role: "Deployer",
    color: "red",
    colorHex: "#ef4444",
    description: "Deploys contracts to Etherlink, verifies them on the explorer, and pushes the final repo to GitHub.",
    skills: [
      { name: "Forge deploy", description: "Runs Foundry deploy scripts with the correct RPC and private key configuration" },
      { name: "Contract verification", description: "Verifies source code on the Etherlink Blockscout explorer post-deployment" },
      { name: "GitHub", description: "Initializes repos, commits build artifacts, and pushes to the project's GitHub org" },
      { name: "Environment setup", description: "Manages .env files, secrets, and deployment configuration for each target network" },
    ],
    owns: ["contracts-evm/script/", "README.md", ".env.example", ".gitignore"],
  },
];

export const AGENTS_BY_SLUG: Record<string, AgentDef> = Object.fromEntries(
  AGENTS.map((a) => [a.slug, a])
);
